---
title: "logistic reg"
author: "Christelle Colin-Leitzinger"
date: "7/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```



```{r}
# Import library
library(tidyverse)
library(data.table)
library(ggplot2)
library(viridis)
library(gtsummary)
library(VennDiagram)
library(ggpubr)
library(survival)
```

```{r}
# Import library
library(tidyverse)
library(data.table)
library(ggplot2)
library(viridis)
library(gtsummary)
library(VennDiagram)
library(ggpubr)
library(survival)

#######################################################################################  I  ### Load data----
path <- fs::path("","Volumes","Gillis_Research","Christelle Colin-Leitzinger", "CHIP_myelosuppression_M4M 2018")
#---
clinical <-
  read_csv(paste0(path, "/data/CHIP_CRASH_data_for_stats_v06.csv")) %>% 
  rename(old_CHIP = CHIP, old_CHPD = CHPD) %>% 
  select(-X32)

CHIP_muts1 <- 
  read_csv(paste0(path, "/data/cleaned CH_myelosupp_muts_2020_CC.csv"))
CHIP_muts <- 
  read.delim(paste0(path, "/data/M4M2018_updated 06.24.20_filtered.txt"))

#######################################################################################  II  ### Data cleaning----
# 2.1.Clinical data----
clinical <- clinical %>% 
  mutate(Cases_Controls = Case_Control) %>% 
  mutate(Case_Control = factor(Case_Control, labels = c("Cases", "Controls"), levels= c(1, 0))) %>% # 0 = ctrl
  # mutate(Case_Control = factor(Case_Control, labels= c("Controls", "Cases"))) %>% 
  mutate(old_CHIP = factor(old_CHIP, labels=c("No CHIP", "CHIP"))) %>% 
  mutate(old_CHPD= factor(old_CHPD, labels=c("No CHPD", "CHPD"))) %>% 
  mutate(Race = factor(Race, labels=c("White", "Other"))) %>% 
  mutate(Gender = factor(Gender, labels = c("Male", "Female"))) %>% 
  mutate(Smoking = factor(Smoking, labels=c("Never","Ever"))) %>% 
  mutate(mets = Mets) %>% 
  mutate(Mets = factor(Mets, labels=c("No", "Yes"))) %>%
  mutate(neutro = Neutro) %>% 
  mutate(Neutro = factor(Neutro, labels=c("No", "Yes"))) %>%
  mutate(anemia = Anemia) %>% 
  mutate(Anemia = factor(Anemia, labels=c("No", "Yes"))) %>%
  mutate(thrombo = Thrombo) %>% 
  mutate(Thrombo = factor(Thrombo, labels=c("No", "Yes"))) %>%
  mutate(leuko = Leuko) %>% 
  mutate(Leuko = factor(Leuko, labels=c("No", "Yes"))) %>%
  mutate(Prior_chemo = factor(Prior_chemo, labels=c("No", "Yes"))) %>% 
  mutate(Prior_rad = factor(Prior_rad, labels=c("No", "Yes"))) %>%
  filter(Cohort == "M4M") # remove later

# 2.2.CHIP data----
CHIP_muts <- full_join(CHIP_muts1 %>% 
                         select(patient_id),
                       CHIP_muts, 
                       by = "patient_id")

# Modified CHIP var to fit with the new data
CHIP_muts <- CHIP_muts %>% 
  mutate(CHIP = case_when(
    is.na(DATA) ~ 0,
    !is.na(DATA) ~ 1
  )) %>% 
  mutate(CHIP = factor(CHIP, labels= c("CHIP", "No CHIP"), levels= c(1, 0)))

#######################################################################################  III  ### Data binding----
# Will bind the 2 data but in 2 different ways 

# 3.1.Bind to have 1 mutation per row, multiple row per patient----
muts_data <- full_join(clinical[3:37], CHIP_muts, 
                          by = c("NGS_ID" = "patient_id")) %>%
  filter(str_detect(NGS_ID, "M4M")) %>% # remove later
  select("NGS_ID", "Case_Control", "Strata", "old_CHIP", "CHIP", everything())
# write_csv(muts_data, paste0(path, "/Output/data output/muts_data.csv"))

# 3.2.Bind to have 1 patient per row, multiple mutation per row----
CHIP_muts1 <- dcast(setDT(CHIP_muts), patient_id ~ rowid(patient_id),
                    value.var = c("GENE", "FUNCTION", "COSMIC", "ESP6500", "VAF", "DEPTH", "CHIP")) %>% 
  select(-CHIP_2, -CHIP_3, -CHIP_4) %>% 
  rename(CHIP = CHIP_1)

global_data <- left_join(clinical[, c(1,3:37)], CHIP_muts1, 
                       by = c("NGS_ID" = "patient_id")) %>% 
  filter(str_detect(NGS_ID, "M4M")) %>% # remove later
  select("Patient", "NGS_ID", "Case_Control", "Strata", "old_CHIP", "CHIP", everything())

# write_csv(global_data, paste0(path, "/Output/data output/global_data.csv"))

rm(CHIP_muts1)

```


```{r, echo= TRUE}
# Linear and Conditionnal Logistic regression----

# 1.Simple check----

# 1.1.Case_Control predicted using Neutro+Anemia+Thrombo+Leuko----
logistic <- clogit(Cases_Controls ~ Neutro+Anemia+Thrombo+Leuko + strata(Strata),
                   data = global_data)
summary(logistic)
summary(table(global_data$Case_Control, global_data$Neutro))
summary(table(global_data$Case_Control, global_data$Anemia))
summary(table(global_data$Case_Control, global_data$Thrombo))
summary(table(global_data$Case_Control, global_data$Leuko))
# 1.2.Case_Control predicted using CBC----
# Case_Control predicted using Base
logistic <- clogit(Cases_Controls ~ BaseANC+BaseHGB+BasePLT+BaseWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ BaseANC+BaseHGB+BasePLT+BaseWBC,
                data = global_data, family = "binomial")
summary(logistic)

# Case_Control predicted using Change
logistic <- clogit(Cases_Controls ~ ChangeANC+ChangeHGB+ChangePLT+ChangeWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# Case_Control predicted using Base + Change
logistic <- clogit(Cases_Controls ~ BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# 1.3.Case_Control predicted using Age----
logistic <- clogit(Cases_Controls ~ Age + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ Age,
                data = global_data, family = "binomial")
summary(logistic)

# 1.4.Case_Control predicted using Gender----
logistic <- clogit(Cases_Controls ~ Gender + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ Gender,
                data = global_data, family = "binomial")
summary(logistic)

# 1.5.Case_Control predicted using Race----
logistic <- clogit(Cases_Controls ~ Race + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ Race,
                data = global_data, family = "binomial")
summary(logistic)

# 1.6.Case_Control predicted using Ethnicity----
logistic <- clogit(Cases_Controls ~ Ethnicity + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ Ethnicity,
                data = global_data, family = "binomial")
summary(logistic)

# 1.7.Case_Control predicted using Age+Gender+Race+Ethnicity----
logistic <- clogit(Cases_Controls ~ Age+Gender+Race+Ethnicity + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ Age+Gender+Race+Ethnicity,
                data = global_data, family = "binomial")
summary(logistic)

# 1.8.Case_Control predicted using Smoking----
logistic <- clogit(Cases_Controls ~ Smoking + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ Smoking,
                data = global_data, family = "binomial")
summary(logistic)

# 1.9.Case_Control predicted using Mets----
logistic <- clogit(Cases_Controls ~ Mets + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ Mets,
                data = global_data, family = "binomial")
summary(logistic)

# 1.10.Case_Control predicted using Smoking+Mets----
logistic <- clogit(Cases_Controls ~ Smoking+Mets + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ Smoking+Mets,
                data = global_data, family = "binomial")
summary(logistic)

# 1.11.Case_Control predicted using CHIP----
logistic <- clogit(Cases_Controls ~ CHIP + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP,
                data = global_data, family = "binomial")
summary(logistic)

# 1.13.Case_Control predicted using Prior_rad----
logistic <- clogit(Cases_Controls ~ Prior_rad + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ Prior_rad,
                data = global_data, family = "binomial")
summary(logistic)

# 1.14.Case_Control predicted using Prior_chemo----
logistic <- clogit(Cases_Controls ~ Prior_chemo + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ Prior_chemo,
                data = global_data, family = "binomial")
summary(logistic)

# 1.15.Case_Control predicted using Prior_rad+Prior_chemo----
logistic <- clogit(Cases_Controls ~ Prior_rad+Prior_chemo + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ Prior_rad+Prior_chemo,
                data = global_data, family = "binomial")
summary(logistic)





# 2.Case_Control predicted using CHIP +----
# 2.1.Case_Control predicted using Neutro+Anemia+Thrombo+Leuko----
logistic <- clogit(Cases_Controls ~ CHIP+Neutro+Anemia+Thrombo+Leuko + strata(Strata),
                   data = global_data)
summary(logistic)
summary(table(global_data$Case_Control, global_data$CHIP, global_data$Neutro))
summary(table(global_data$Case_Control, global_data$CHIP, global_data$Anemia))
summary(table(global_data$Case_Control, global_data$CHIP, global_data$Thrombo))
summary(table(global_data$Case_Control, global_data$CHIP, global_data$Leuko))
# 2.2.Case_Control predicted using CBC----
# Case_Control predicted using Base
logistic <- clogit(Cases_Controls ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC,
                data = global_data, family = "binomial")
summary(logistic)

# Case_Control predicted using Change
logistic <- clogit(Cases_Controls ~ CHIP+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# Case_Control predicted using Base + Change
logistic <- clogit(Cases_Controls ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# 2.3.Case_Control predicted using Age----
logistic <- clogit(Cases_Controls ~ CHIP+Age + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Age,
                data = global_data, family = "binomial")
summary(logistic)

# 2.4.Case_Control predicted using Gender----
logistic <- clogit(Cases_Controls ~ CHIP+Gender + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Gender,
                data = global_data, family = "binomial")
summary(logistic)

# 2.5.Case_Control predicted using Race----
logistic <- clogit(Cases_Controls ~ CHIP+Race + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Race,
                data = global_data, family = "binomial")
summary(logistic)

# 2.6.Case_Control predicted using Ethnicity----
logistic <- clogit(Cases_Controls ~ CHIP+Ethnicity + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Ethnicity,
                data = global_data, family = "binomial")
summary(logistic)

# 2.7.Case_Control predicted using Age+Gender+Race+Ethnicity----
logistic <- clogit(Cases_Controls ~ CHIP+Age+Gender+Race+Ethnicity + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Age+Gender+Race+Ethnicity,
                data = global_data, family = "binomial")
summary(logistic)

# 2.8.Case_Control predicted using Smoking----
logistic <- clogit(Cases_Controls ~ CHIP+Smoking + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Smoking,
                data = global_data, family = "binomial")
summary(logistic)

# 2.9.Case_Control predicted using Mets----
logistic <- clogit(Cases_Controls ~ CHIP+Mets + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Mets,
                data = global_data, family = "binomial")
summary(logistic)

# 2.10.Case_Control predicted using Smoking+Mets----
logistic <- clogit(Cases_Controls ~ CHIP+Smoking+Mets + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Smoking+Mets,
                data = global_data, family = "binomial")
summary(logistic)

# 2.11.Case_Control predicted using Prior_rad----
logistic <- clogit(Cases_Controls ~ CHIP+Prior_rad + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Prior_rad,
                data = global_data, family = "binomial")
summary(logistic)

# 2.12.Case_Control predicted using Prior_chemo----
logistic <- clogit(Cases_Controls ~ CHIP+Prior_chemo + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Prior_chemo,
                data = global_data, family = "binomial")
summary(logistic)

# 2.13.Case_Control predicted using Prior_rad+Prior_chemo----
logistic <- clogit(Cases_Controls ~ CHIP+Prior_rad+Prior_chemo + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Prior_rad+Prior_chemo,
                data = global_data, family = "binomial")
summary(logistic)

# 2.14.All var----
logistic <- clogit(Cases_Controls ~ CHIP+Age+Gender+Race+Ethnicity+Smoking+Mets+
                     Prior_chemo+Prior_rad, data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Age+Gender+Race+Ethnicity+Smoking+Mets+
                  Prior_chemo+Prior_rad, data = global_data, family = "binomial")
summary(logistic)




# 3.More complexe models----
# 3.1.Case_Control predicted CHIP +----


# CHIP+CBC+, Age increase p
logistic <- clogit(Cases_Controls ~ CHIP+Age+BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                   data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Age+BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# CHIP+CBC+, Age+Race increse p even if better then Age alone
logistic <- clogit(Cases_Controls ~ CHIP+Age+Race+BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                   data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Age+Race+BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# CHIP+CBC+, Age+Race+Ethnicity
logistic <- clogit(Cases_Controls ~ CHIP+Age+Race+Ethnicity+
                     BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                   data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Age+Race+Ethnicity+
                  BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# CHIP+CBC+, Age+Race+Ethnicity+Smoking
logistic <- clogit(Cases_Controls ~ CHIP+Age+Race+Ethnicity+Smoking+
                     BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                   data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Age+Race+Ethnicity+Smoking+
                  BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# CHIP+CBC+, Age+Race+Ethnicity+Smoking+Mets
logistic <- clogit(Cases_Controls ~ CHIP+Age+Race+Ethnicity+Smoking+Mets+
                     BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                   data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Age+Race+Ethnicity+Smoking+Mets+
                  BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# CHIP+CBC+, Age+Race+Ethnicity+Smoking+Mets+Prior_rad
logistic <- clogit(Cases_Controls ~ CHIP+Age+Race+Ethnicity+Smoking+Mets+Prior_rad+
                     BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                   data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Age+Race+Ethnicity+Smoking+Mets+Prior_rad+
                  BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)
# CHIP+CBC+, Age+Race+Ethnicity+Smoking+Mets+Prior_rad+Prior_chemo
logistic <- clogit(Cases_Controls ~ CHIP+Age+Race+Ethnicity+Smoking+Mets+Prior_rad+Prior_chemo+
                     BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                   data = global_data)
summary(logistic)
logistic <- glm(Cases_Controls ~ CHIP+Age+Race+Ethnicity+Smoking+Mets+Prior_rad+Prior_chemo+
                  BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)










# 4.Neutro predicted using CHIP +----
# 4.1.Neutro predicted using Neutro+Anemia+Thrombo+Leuko----
logistic <- clogit(neutro ~ CHIP+Anemia+Thrombo+Leuko + strata(Strata),
                   data = global_data)
summary(logistic)
summary(table(global_data$Neutro, global_data$CHIP, global_data$Anemia))
summary(table(global_data$Neutro, global_data$CHIP, global_data$Thrombo))
summary(table(global_data$Neutro, global_data$CHIP, global_data$Leuko))
# 4.2.Neutro predicted using CBC----
# Neutro predicted using Base
logistic <- clogit(neutro ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(neutro ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC,
                data = global_data, family = "binomial")
summary(logistic)

# Neutro predicted using Change
logistic <- clogit(neutro ~ CHIP+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(neutro ~ CHIP+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# Neutro predicted using Base + Change
logistic <- clogit(neutro ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(neutro ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# 4.3.Neutro predicted using Age----
logistic <- clogit(neutro ~ CHIP+Age + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(neutro ~ CHIP+Age,
                data = global_data, family = "binomial")
summary(logistic)

# 4.4.Neutro predicted using Gender----
logistic <- clogit(neutro ~ CHIP+Gender + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(neutro ~ CHIP+Gender,
                data = global_data, family = "binomial")
summary(logistic)

# 4.5.Neutro predicted using Race----
logistic <- clogit(neutro ~ CHIP+Race + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(neutro ~ CHIP+Race,
                data = global_data, family = "binomial")
summary(logistic)

# 4.6.Neutro predicted using Ethnicity----
logistic <- clogit(neutro ~ CHIP+Ethnicity + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(neutro ~ CHIP+Ethnicity,
                data = global_data, family = "binomial")
summary(logistic)

# 4.7.Neutro predicted using Age+Gender+Race+Ethnicity----
logistic <- clogit(neutro ~ CHIP+Age+Gender+Race+Ethnicity + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(neutro ~ CHIP+Age+Gender+Race+Ethnicity,
                data = global_data, family = "binomial")
summary(logistic)

# 4.8.Neutro predicted using Smoking----
logistic <- clogit(neutro ~ CHIP+Smoking + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(neutro ~ CHIP+Smoking,
                data = global_data, family = "binomial")
summary(logistic)

# 4.9.Neutro predicted using Mets----
logistic <- clogit(neutro ~ CHIP+Mets + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(neutro ~ CHIP+Mets,
                data = global_data, family = "binomial")
summary(logistic)

# 4.10.Neutro predicted using Smoking+Mets----
logistic <- clogit(neutro ~ CHIP+Smoking+Mets + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(neutro ~ CHIP+Smoking+Mets,
                data = global_data, family = "binomial")
summary(logistic)

# 4.11.Neutro predicted using Prior_rad----
logistic <- clogit(neutro ~ CHIP+Prior_rad + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(neutro ~ CHIP+Prior_rad,
                data = global_data, family = "binomial")
summary(logistic)

# 4.12.Neutro predicted using Prior_chemo----
logistic <- clogit(neutro ~ CHIP+Prior_chemo + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(neutro ~ CHIP+Prior_chemo,
                data = global_data, family = "binomial")
summary(logistic)

# 4.13.Neutro predicted using Prior_rad+Prior_chemo----
logistic <- clogit(neutro ~ CHIP+Prior_rad+Prior_chemo + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(neutro ~ CHIP+Prior_rad+Prior_chemo,
                data = global_data, family = "binomial")
summary(logistic)

# 4.14.All var----
logistic <- clogit(neutro ~ CHIP+Age+Gender+Race+Ethnicity+Smoking+Mets+
                     Prior_chemo+Prior_rad, data = global_data)
summary(logistic)
logistic <- glm(neutro ~ CHIP+Age+Gender+Race+Ethnicity+Smoking+Mets+
                  Prior_chemo+Prior_rad, data = global_data, family = "binomial")
summary(logistic)


# 5.Anemia predicted using CHIP +----
# 5.1.Anemia predicted using Neutro+Anemia+Thrombo+Leuko----
logistic <- clogit(anemia ~ CHIP+Neutro+Thrombo+Leuko + strata(Strata),
                   data = global_data)
summary(logistic)
summary(table(global_data$Anemia, global_data$CHIP, global_data$Neutro))
summary(table(global_data$Anemia, global_data$CHIP, global_data$Thrombo))
summary(table(global_data$Anemia, global_data$CHIP, global_data$Leuko))
# 5.2.Anemia predicted using CBC----
# Anemia predicted using Base
logistic <- clogit(anemia ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(anemia ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC,
                data = global_data, family = "binomial")
summary(logistic)

# Anemia predicted using Change
logistic <- clogit(anemia ~ CHIP+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(anemia ~ CHIP+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# Anemia predicted using Base + Change
logistic <- clogit(anemia ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(anemia ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# 5.3.Anemia predicted using Age----
logistic <- clogit(anemia ~ CHIP+Age + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(anemia ~ CHIP+Age,
                data = global_data, family = "binomial")
summary(logistic)

# 5.4.Anemia predicted using Gender----
logistic <- clogit(anemia ~ CHIP+Gender + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(anemia ~ CHIP+Gender,
                data = global_data, family = "binomial")
summary(logistic)

# 5.5.Anemia predicted using Race----
logistic <- clogit(anemia ~ CHIP+Race + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(anemia ~ CHIP+Race,
                data = global_data, family = "binomial")
summary(logistic)

# 5.6.Anemia predicted using Ethnicity----
logistic <- clogit(anemia ~ CHIP+Ethnicity + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(anemia ~ CHIP+Ethnicity,
                data = global_data, family = "binomial")
summary(logistic)

# 5.7.Anemia predicted using Age+Gender+Race+Ethnicity----
logistic <- clogit(anemia ~ CHIP+Age+Gender+Race+Ethnicity + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(anemia ~ CHIP+Age+Gender+Race+Ethnicity,
                data = global_data, family = "binomial")
summary(logistic)

# 5.8.Anemia predicted using Smoking----
logistic <- clogit(anemia ~ CHIP+Smoking + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(anemia ~ CHIP+Smoking,
                data = global_data, family = "binomial")
summary(logistic)

# 5.9.Anemia predicted using Mets----
logistic <- clogit(anemia ~ CHIP+Mets + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(anemia ~ CHIP+Mets,
                data = global_data, family = "binomial")
summary(logistic)

# 5.10.Anemia predicted using Smoking+Mets----
logistic <- clogit(anemia ~ CHIP+Smoking+Mets + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(anemia ~ CHIP+Smoking+Mets,
                data = global_data, family = "binomial")
summary(logistic)

# 5.11.Anemia predicted using Prior_rad----
logistic <- clogit(anemia ~ CHIP+Prior_rad + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(anemia ~ CHIP+Prior_rad,
                data = global_data, family = "binomial")
summary(logistic)

# 5.12.Anemia predicted using Prior_chemo----
logistic <- clogit(anemia ~ CHIP+Prior_chemo + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(anemia ~ CHIP+Prior_chemo,
                data = global_data, family = "binomial")
summary(logistic)

# 5.13.Anemia predicted using Prior_rad+Prior_chemo----
logistic <- clogit(anemia ~ CHIP+Prior_rad+Prior_chemo + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(anemia ~ CHIP+Prior_rad+Prior_chemo,
                data = global_data, family = "binomial")
summary(logistic)

# 5.14.All var----
logistic <- clogit(anemia ~ CHIP+Age+Gender+Race+Ethnicity+Smoking+Mets+
                     Prior_chemo+Prior_rad, data = global_data)
summary(logistic)
logistic <- glm(anemia ~ CHIP+Age+Gender+Race+Ethnicity+Smoking+Mets+
                  Prior_chemo+Prior_rad, data = global_data, family = "binomial")
summary(logistic)


# 6.Thrombo predicted using CHIP +----
# 6.1.Neutropredicted using Neutro+Anemia+Thrombo+Leuko----
logistic <- clogit(thrombo ~ CHIP+Neutro+Anemia+Leuko + strata(Strata),
                   data = global_data)
summary(logistic)
summary(table(global_data$Thrombo, global_data$CHIP, global_data$Neutro))
summary(table(global_data$Thrombo, global_data$CHIP, global_data$Anemia))
summary(table(global_data$Thrombo, global_data$CHIP, global_data$Leuko))
# 6.2.Thrombo predicted using CBC----
# Thrombo predicted using Base
logistic <- clogit(thrombo ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(thrombo ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC,
                data = global_data, family = "binomial")
summary(logistic)

# Thrombo predicted using Change
logistic <- clogit(thrombo ~ CHIP+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(thrombo ~ CHIP+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# Thrombo predicted using Base + Change
logistic <- clogit(thrombo ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(thrombo ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# 6.3.Thrombo predicted using Age----
logistic <- clogit(thrombo ~ CHIP+Age + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(thrombo ~ CHIP+Age,
                data = global_data, family = "binomial")
summary(logistic)

# 6.4.Thrombo predicted using Gender----
logistic <- clogit(thrombo ~ CHIP+Gender + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(thrombo ~ CHIP+Gender,
                data = global_data, family = "binomial")
summary(logistic)

# 6.5.Thrombo predicted using Race----
logistic <- clogit(thrombo ~ CHIP+Race + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(thrombo ~ CHIP+Race,
                data = global_data, family = "binomial")
summary(logistic)

# 6.6.Thrombo predicted using Ethnicity----
logistic <- clogit(thrombo ~ CHIP+Ethnicity + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(thrombo ~ CHIP+Ethnicity,
                data = global_data, family = "binomial")
summary(logistic)

# 6.7.Thrombo predicted using Age+Gender+Race+Ethnicity----
logistic <- clogit(thrombo ~ CHIP+Age+Gender+Race+Ethnicity + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(thrombo ~ CHIP+Age+Gender+Race+Ethnicity,
                data = global_data, family = "binomial")
summary(logistic)

# 6.8.Thrombo predicted using Smoking----
logistic <- clogit(thrombo ~ CHIP+Smoking + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(thrombo ~ CHIP+Smoking,
                data = global_data, family = "binomial")
summary(logistic)

# 6.9.Thrombo predicted using Mets----
logistic <- clogit(thrombo ~ CHIP+Mets + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(thrombo ~ CHIP+Mets,
                data = global_data, family = "binomial")
summary(logistic)

# 6.10.Thrombo predicted using Smoking+Mets----
logistic <- clogit(thrombo ~ CHIP+Smoking+Mets + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(thrombo ~ CHIP+Smoking+Mets,
                data = global_data, family = "binomial")
summary(logistic)

# 6.11.Thrombo predicted using Prior_rad----
logistic <- clogit(thrombo ~ CHIP+Prior_rad + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(thrombo ~ CHIP+Prior_rad,
                data = global_data, family = "binomial")
summary(logistic)

# 6.12.Thrombo predicted using Prior_chemo----
logistic <- clogit(thrombo ~ CHIP+Prior_chemo + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(thrombo ~ CHIP+Prior_chemo,
                data = global_data, family = "binomial")
summary(logistic)

# 6.13.Thrombo predicted using Prior_rad+Prior_chemo----
logistic <- clogit(thrombo ~ CHIP+Prior_rad+Prior_chemo + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(thrombo ~ CHIP+Prior_rad+Prior_chemo,
                data = global_data, family = "binomial")
summary(logistic)

# 6.14.All var----
logistic <- clogit(thrombo ~ CHIP+Age+Gender+Race+Ethnicity+Smoking+Mets+
                     Prior_chemo+Prior_rad, data = global_data)
summary(logistic)
logistic <- glm(thrombo ~ CHIP+Age+Gender+Race+Ethnicity+Smoking+Mets+
                  Prior_chemo+Prior_rad, data = global_data, family = "binomial")
summary(logistic)


# 7.Leuko predicted using CHIP +----
# 7.1.Leuko predicted using Neutro+Anemia+Thrombo+Leuko----
logistic <- clogit(leuko ~ CHIP+Neutro+Thrombo+Anemia + strata(Strata),
                   data = global_data)
summary(logistic)
summary(table(global_data$Leuko, global_data$CHIP, global_data$Neutro))
summary(table(global_data$Leuko, global_data$CHIP, global_data$Anemia))
summary(table(global_data$Leuko, global_data$CHIP, global_data$Thrombo))
# 7.2.Leuko predicted using CBC----
# Leuko predicted using Base
logistic <- clogit(leuko ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(leuko ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC,
                data = global_data, family = "binomial")
summary(logistic)

# Leuko predicted using Change
logistic <- clogit(leuko ~ CHIP+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(leuko ~ CHIP+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# Leuko predicted using Base + Change
logistic <- clogit(leuko ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(leuko ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# 7.3.Leuko predicted using Age----
logistic <- clogit(leuko ~ CHIP+Age + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(leuko ~ CHIP+Age,
                data = global_data, family = "binomial")
summary(logistic)

# 7.4.Leuko predicted using Gender----
logistic <- clogit(leuko ~ CHIP+Gender + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(leuko ~ CHIP+Gender,
                data = global_data, family = "binomial")
summary(logistic)

# 7.5.Leuko predicted using Race----
logistic <- clogit(leuko ~ CHIP+Race + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(leuko ~ CHIP+Race,
                data = global_data, family = "binomial")
summary(logistic)

# 7.6.Leuko predicted using Ethnicity----
logistic <- clogit(leuko ~ CHIP+Ethnicity + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(leuko ~ CHIP+Ethnicity,
                data = global_data, family = "binomial")
summary(logistic)

# 7.7.Leuko predicted using Age+Gender+Race+Ethnicity----
logistic <- clogit(leuko ~ CHIP+Age+Gender+Race+Ethnicity + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(leuko ~ CHIP+Age+Gender+Race+Ethnicity,
                data = global_data, family = "binomial")
summary(logistic)

# 7.8.Leuko predicted using Smoking----
logistic <- clogit(leuko ~ CHIP+Smoking + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(leuko ~ CHIP+Smoking,
                data = global_data, family = "binomial")
summary(logistic)

# 7.9.Leuko predicted using Mets----
logistic <- clogit(leuko ~ CHIP+Mets + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(leuko ~ CHIP+Mets,
                data = global_data, family = "binomial")
summary(logistic)

# 7.10.Leuko predicted using Smoking+Mets----
logistic <- clogit(leuko ~ CHIP+Smoking+Mets + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(leuko ~ CHIP+Smoking+Mets,
                data = global_data, family = "binomial")
summary(logistic)

# 7.11.Leuko predicted using Prior_rad----
logistic <- clogit(leuko ~ CHIP+Prior_rad + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(leuko ~ CHIP+Prior_rad,
                data = global_data, family = "binomial")
summary(logistic)

# 7.12.Leuko predicted using Prior_chemo----
logistic <- clogit(leuko ~ CHIP+Prior_chemo + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(leuko ~ CHIP+Prior_chemo,
                data = global_data, family = "binomial")
summary(logistic)

# 7.13.Leuko predicted using Prior_rad+Prior_chemo----
logistic <- clogit(leuko ~ CHIP+Prior_rad+Prior_chemo + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(leuko ~ CHIP+Prior_rad+Prior_chemo,
                data = global_data, family = "binomial")
summary(logistic)

# 7.14.All var----
logistic <- clogit(leuko ~ CHIP+Age+Gender+Race+Ethnicity+Smoking+Mets+
                     Prior_chemo+Prior_rad, data = global_data)
summary(logistic)
logistic <- glm(leuko ~ CHIP+Age+Gender+Race+Ethnicity+Smoking+Mets+
                     Prior_chemo+Prior_rad, data = global_data, family = "binomial")
summary(logistic)



# 8.Mets predicted using CHIP +----
# 8.1.Mets predicted using Neutro+Anemia+Thrombo+Leuko----
logistic <- clogit(mets ~ CHIP+Neutro+Thrombo+Anemia+Leuko + strata(Strata),
                   data = global_data)
summary(logistic)
summary(table(global_data$mets, global_data$CHIP, global_data$Neutro))
summary(table(global_data$mets, global_data$CHIP, global_data$Anemia))
summary(table(global_data$mets, global_data$CHIP, global_data$Thrombo))
summary(table(global_data$mets, global_data$CHIP, global_data$Leuko))
# 8.2.Mets predicted using CBC----
# Mets predicted using Base
logistic <- clogit(mets ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(mets ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC,
                data = global_data, family = "binomial")
summary(logistic)

# Mets predicted using Change
logistic <- clogit(mets ~ CHIP+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(mets ~ CHIP+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# Mets predicted using Base + Change
logistic <- clogit(mets ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC + strata(Strata),
                   data = global_data)
summary(logistic)
logistic <- glm(mets ~ CHIP+BaseANC+BaseHGB+BasePLT+BaseWBC+ChangeANC+ChangeHGB+ChangePLT+ChangeWBC,
                data = global_data, family = "binomial")
summary(logistic)

# 8.3.Mets predicted using Age----
logistic <- clogit(mets ~ CHIP+Age + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(mets ~ CHIP+Age,
                data = global_data, family = "binomial")
summary(logistic)

# 8.4.Mets predicted using Gender----
logistic <- clogit(mets ~ CHIP+Gender + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(mets ~ CHIP+Gender,
                data = global_data, family = "binomial")
summary(logistic)

# 8.5.Mets predicted using Race----
logistic <- clogit(mets ~ CHIP+Race + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(mets ~ CHIP+Race,
                data = global_data, family = "binomial")
summary(logistic)

# 8.6.Mets predicted using Ethnicity----
logistic <- clogit(mets ~ CHIP+Ethnicity + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(mets ~ CHIP+Ethnicity,
                data = global_data, family = "binomial")
summary(logistic)

# 8.7.Mets predicted using Age+Gender+Race+Ethnicity----
logistic <- clogit(mets ~ CHIP+Age+Gender+Race+Ethnicity + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(mets ~ CHIP+Age+Gender+Race+Ethnicity,
                data = global_data, family = "binomial")
summary(logistic)

# 8.8.Mets predicted using Smoking----
logistic <- clogit(mets ~ CHIP+Smoking + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(mets ~ CHIP+Smoking,
                data = global_data, family = "binomial")
summary(logistic)

# 8.9.Mets predicted using Prior_rad----
logistic <- clogit(mets ~ CHIP+Prior_rad + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(mets ~ CHIP+Prior_rad,
                data = global_data, family = "binomial")
summary(logistic)

# 8.10.Mets predicted using Prior_chemo----
logistic <- clogit(mets ~ CHIP+Prior_chemo + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(mets ~ CHIP+Prior_chemo,
                data = global_data, family = "binomial")
summary(logistic)

# 8.11.Mets predicted using Prior_rad+Prior_chemo----
logistic <- clogit(mets ~ CHIP+Prior_rad+Prior_chemo + strata(Strata), data = global_data)
summary(logistic)
logistic <- glm(mets ~ CHIP+Prior_rad+Prior_chemo,
                data = global_data, family = "binomial")
summary(logistic)

# 8.12.All var----
logistic <- clogit(mets ~ CHIP+Age+Gender+Race+Ethnicity+Smoking+
                     Prior_chemo+Prior_rad, data = global_data)
summary(logistic)
logistic <- glm(mets ~ CHIP+Age+Gender+Race+Ethnicity+Smoking+
                  Prior_chemo+Prior_rad, data = global_data, family = "binomial")
summary(logistic)

```

***
# Nancy's code with new data
```{r, echo= TRUE}
####Conditional logistic regression: Myelosupp and CHIP only
res.clogit1 <- clogit(Cases_Controls ~ CHIP + strata(Strata), data = global_data, id=NGS_ID)
summ.clogit1 <- summary(res.clogit1)
summ.clogit1
exp(cbind(coef(res.clogit1), confint(res.clogit1)))

##Conditional: Myelosupp~CHIP, age, gender, race, MAX2
res.clogit2 <- clogit(Cases_Controls ~ CHIP + Age + Gender + Race + MAX2heme + strata(Strata), data = global_data)
summ.clogit2 <- summary(res.clogit2)
summ.clogit2
exp(cbind(coef(res.clogit2), confint(res.clogit2)))

##Conditional: Myelosupp~CHIP, all variables
res.clogit3 <- clogit(Cases_Controls ~ CHIP + Age + Gender + Race + Smoking + Mets + BaseANC + BaseHGB + BasePLT + BaseWBC + Prior_chemo + Prior_rad + MAX2heme + strata(Strata), data = global_data)
summ.clogit3 <- summary(res.clogit3)
summ.clogit3
exp(cbind(coef(res.clogit3), confint(res.clogit3)))

##Conditional: Myelosupp~CHIP, clinical variables -- in Moffitt job talk
res.clogit4 <- clogit(Cases_Controls ~ CHIP + Age + Mets + BaseANC + BaseHGB + BasePLT + BaseWBC + Prior_chemo + Prior_rad + MAX2heme + strata(Strata), data = global_data)
summ.clogit4 <- summary(res.clogit4)
summ.clogit4
exp(cbind(coef(res.clogit4), confint(res.clogit4)))

##Conditional: Myelosupp~CHIP, clinical variables -- in MSK job talk
res.clogit4 <- clogit(Cases_Controls ~ CHIP + Age + Gender + BaseANC + BaseHGB + BasePLT + BaseWBC + Prior_chemo + Prior_rad + MAX2heme + strata(Strata), data = global_data)
summ.clogit4 <- summary(res.clogit4)
summ.clogit4
exp(cbind(coef(res.clogit4), confint(res.clogit4)))

##Conditional: Myelosupp~CHIP, baseline labs, MAX2
res.clogit5 <- clogit(Cases_Controls ~ CHIP + BaseANC + BaseHGB + BasePLT + BaseWBC + MAX2heme + strata(Strata), data = global_data)
summ.clogit5 <- summary(res.clogit5)
summ.clogit5
exp(cbind(coef(res.clogit5), confint(res.clogit5)))



##Age by Case_Control 
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(Age, na.rm = TRUE),
    IQR = IQR(Age, na.rm = TRUE)
  )

res <- wilcox.test(Age ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Sex by Case_Control
table(global_data$Case_Control, global_data$Gender)
Case_Controlsex <- table(global_data$Case_Control, global_data$Gender)
summary(Case_Controlsex)
#fisher.test(table (global_data$Case_Control, global_data$Gender))

##Race by Case_Control
table(global_data$Case_Control, global_data$Race)
Case_Controlrace <- table(global_data$Case_Control, global_data$Race)
# summary(Case_Controlrace)
fisher.test(table (global_data$Case_Control, global_data$Race))

##Smoking by Case_Control 
table(global_data$Case_Control, global_data$Smoking)
Case_ControlSmoking <- table(global_data$Case_Control, global_data$Smoking)
summary(Case_ControlSmoking)
# fisher.test(table (global_data$Case_Control, global_data$Smoking))

##Metastasis by Case_Control
table(global_data$Case_Control, global_data$Mets)
Case_ControlMets <- table(global_data$Case_Control, global_data$Mets)
summary(Case_ControlMets)
# fisher.test(table (global_data$Case_Control, global_data$Mets))

##Prior Chemotherapy by Case_Control
table(global_data$Case_Control, global_data$Prior_chemo)
Case_Controlchemo <- table(global_data$Case_Control, global_data$Prior_chemo)
summary(Case_Controlchemo)
# fisher.test(table (global_data$Case_Control, global_data$Prior_chemo))

##Prior Radiation by Case_Control
table(global_data$Case_Control, global_data$Prior_rad)
Case_Controlrad <- table(global_data$Case_Control, global_data$Prior_rad)
summary(Case_Controlrad)
# fisher.test(table (global_data$Case_Control, global_data$Prior_rad))

##MAX2-heme by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(MAX2heme, na.rm = TRUE),
    IQR = IQR(MAX2heme, na.rm = TRUE)
  )
res <- wilcox.test(MAX2heme ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Baseline ANC by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(BaseANC, na.rm = TRUE),
    IQR = IQR(BaseANC, na.rm = TRUE)
  )
res <- wilcox.test(BaseANC ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Baseline HGB by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(BaseHGB, na.rm = TRUE),
    IQR = IQR(BaseHGB, na.rm = TRUE)
  )
res <- wilcox.test(BaseHGB ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Baseline PLT by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(BasePLT, na.rm = TRUE),
    IQR = IQR(BasePLT, na.rm = TRUE)
  )
res <- wilcox.test(BasePLT ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Baseline WBC by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(BaseWBC, na.rm = TRUE),
    IQR = IQR(BaseWBC, na.rm = TRUE)
  )
res <- wilcox.test(BaseWBC ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Change in ANC by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(ChangeANC, na.rm = TRUE),
    IQR = IQR(ChangeANC, na.rm = TRUE)
  )
res <- wilcox.test(ChangeANC ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Change in HGB by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(ChangeHGB, na.rm = TRUE),
    IQR = IQR(ChangeHGB, na.rm = TRUE)
  )
res <- wilcox.test(ChangeHGB ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Change in PLT by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(ChangePLT, na.rm = TRUE),
    IQR = IQR(ChangePLT, na.rm = TRUE)
  )
res <- wilcox.test(ChangePLT ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Change in WBC by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(ChangeWBC, na.rm = TRUE),
    IQR = IQR(ChangeWBC, na.rm = TRUE)
  )
res <- wilcox.test(ChangeWBC ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Neutopenia by Case_Control
table(global_data$Case_Control, global_data$Neutro)
Case_ControlNeutro <- table(global_data$Case_Control, global_data$Neutro)
summary(Case_ControlNeutro)
# fisher.test(table (global_data$Case_Control, global_data$Neutro))

##Anemia by Case_Control
table(global_data$Case_Control, global_data$Anemia)
Case_ControlAnemia <- table(global_data$Case_Control, global_data$Anemia)
# summary(Case_ControlAnemia)
fisher.test(table (global_data$Case_Control, global_data$Anemia))

##Thrombocytopenia by Case_Control
table(global_data$Case_Control, global_data$Thrombo)
Case_ControlThrombo <- table(global_data$Case_Control, global_data$Thrombo)
# summary(Case_ControlThrombo)
fisher.test(table (global_data$Case_Control, global_data$Thrombo))

##Leukopenia by Case_Control
table(global_data$Case_Control, global_data$Leuko)
Case_ControlLeuko <- table(global_data$Case_Control, global_data$Leuko)
summary(Case_ControlLeuko)
# fisher.test(table (global_data$Case_Control, global_data$Leuko))





#### global_data only - By CHIP status----


##Age by CHIP 
global_data %>% group_by(CHIP) %>%
  summarise(
    count = n(),
    median = median(Age, na.rm = TRUE),
    IQR = IQR(Age, na.rm = TRUE)
  )

res <- wilcox.test(Age ~ CHIP, data = global_data,
                   exact = FALSE)
res

##Sex by CHIP
table(global_data$CHIP, global_data$Gender)
CHIPsex <- table(global_data$CHIP, global_data$Gender)
summary(CHIPsex)
#fisher.test(table (global_data$CHIP, global_data$Gender))

##Race by CHIP
table(global_data$CHIP, global_data$Race)
CHIPrace <- table(global_data$CHIP, global_data$Race)
# summary(CHIPrace)
fisher.test(table (global_data$CHIP, global_data$Race))

##Smoking by CHIP 
table(global_data$CHIP, global_data$Smoking)
CHIPSmoking <- table(global_data$CHIP, global_data$Smoking)
summary(CHIPSmoking)
# fisher.test(table (global_data$CHIP, global_data$Smoking))


##Metastasis by CHIP
table(global_data$CHIP, global_data$Mets)
CHIPMets <- table(global_data$CHIP, global_data$Mets)
summary(CHIPMets)
# fisher.test(table (global_data$CHIP, global_data$Mets))

##Prior Chemotherapy by CHIP
table(global_data$CHIP, global_data$Prior_chemo)
CHIPchemo <- table(global_data$CHIP, global_data$Prior_chemo)
summary(CHIPchemo)
# fisher.test(table (global_data$CHIP, global_data$Prior_chemo))

##Prior Radiation by CHIP
table(global_data$CHIP, global_data$Prior_rad)
CHIPrad <- table(global_data$CHIP, global_data$Prior_rad)
summary(CHIPrad)
# fisher.test(table (global_data$CHIP, global_data$Prior_rad))


##Baseline ANC by CHIP
global_data %>% group_by(CHIP) %>%
  summarise(
    count = n(),
    median = median(BaseANC, na.rm = TRUE),
    IQR = IQR(BaseANC, na.rm = TRUE)
  )
res <- wilcox.test(BaseANC ~ CHIP, data = global_data,
                   exact = FALSE)
res


##Baseline HGB by CHIP
group_by(global_data, CHIP) %>%
  summarise(
    count = n(),
    median = median(BaseHGB, na.rm = TRUE),
    IQR = IQR(BaseHGB, na.rm = TRUE)
  )
res <- wilcox.test(BaseHGB ~ CHIP, data = global_data,
                   exact = FALSE)
res


##Baseline PLT by CHIP
group_by(global_data, CHIP) %>%
  summarise(
    count = n(),
    median = median(BasePLT, na.rm = TRUE),
    IQR = IQR(BasePLT, na.rm = TRUE)
  )
res <- wilcox.test(BasePLT ~ CHIP, data = global_data,
                   exact = FALSE)
res


##Baseline WBC by CHIP
group_by(global_data, CHIP) %>%
  summarise(
    count = n(),
    median = median(BaseWBC, na.rm = TRUE),
    IQR = IQR(BaseWBC, na.rm = TRUE)
  )
res <- wilcox.test(BaseWBC ~ CHIP, data = global_data,
                   exact = FALSE)
res


##Change in ANC by CHIP
group_by(global_data, CHIP) %>%
  summarise(
    count = n(),
    median = median(ChangeANC, na.rm = TRUE),
    IQR = IQR(ChangeANC, na.rm = TRUE)
  )
res <- wilcox.test(ChangeANC ~ CHIP, data = global_data,
                   exact = FALSE)
res


##Change in HGB by CHIP
group_by(global_data, CHIP) %>%
  summarise(
    count = n(),
    median = median(ChangeHGB, na.rm = TRUE),
    IQR = IQR(ChangeHGB, na.rm = TRUE)
  )
res <- wilcox.test(ChangeHGB ~ CHIP, data = global_data,
                   exact = FALSE)
res


##Change in PLT by CHIP
group_by(global_data, CHIP) %>%
  summarise(
    count = n(),
    median = median(ChangePLT, na.rm = TRUE),
    IQR = IQR(ChangePLT, na.rm = TRUE)
  )
res <- wilcox.test(ChangePLT ~ CHIP, data = global_data,
                   exact = FALSE)
res


##Change in WBC by CHIP
group_by(global_data, CHIP) %>%
  summarise(
    count = n(),
    median = median(ChangeWBC, na.rm = TRUE),
    IQR = IQR(ChangeWBC, na.rm = TRUE)
  )
res <- wilcox.test(ChangeWBC ~ CHIP, data = global_data,
                   exact = FALSE)
res


##Neutopenia by CHIP
table(global_data$CHIP, global_data$Neutro)
CHIPNeutro <- table(global_data$CHIP, global_data$Neutro)
summary(CHIPNeutro)
# fisher.test(table (global_data$CHIP, global_data$Neutro))


##Anemia by CHIP
table(global_data$CHIP, global_data$Anemia)
CHIPAnemia <- table(global_data$CHIP, global_data$Anemia)
# summary(CHIPAnemia)
fisher.test(table (global_data$CHIP, global_data$Anemia))


##Thrombocytopenia by CHIP
table(global_data$CHIP, global_data$Thrombo)
CHIPThrombo <- table(global_data$CHIP, global_data$Thrombo)
# summary(CHIPThrombo)
fisher.test(table (global_data$CHIP, global_data$Thrombo))

##Leukopenia by CHIP
table(global_data$CHIP, global_data$Leuko)
CHIPLeuko <- table(global_data$CHIP, global_data$Leuko)
summary(CHIPLeuko)
# fisher.test(table (global_data$CHIP, global_data$Leuko))




####Combined M4M and UNC cohort----

#Association between myelopsuppression and CHIP 
table(global_data$Case_Control, global_data$CHIP)
CHIPmyelo <- table(global_data$Case_Control, global_data$CHIP)
summary(CHIPmyelo)
fisher.test(table (global_data$Case_Control, global_data$CHIP))

res.logit1b <- glm(Case_Control ~ CHIP, data = global_data, family = "binomial")
summary(res.logit1b)$coef
exp(cbind(coef(res.logit1b), confint(res.logit1b)))

##Adjusted - myelosuppression and CHIP -- Moffitt job talk
CHIP_myelo_adj <-glm(Case_Control ~ CHIP + Age + Mets + BaseANC + BaseHGB + BasePLT + BaseWBC + Prior_chemo + Prior_rad + MAX2heme, data = global_data, family = binomial(link='logit'))
summary(CHIP_myelo_adj)
exp(cbind(coef(CHIP_myelo_adj), confint(CHIP_myelo_adj)))

##Adjusted - myelosuppression and CHIP -- MSK job talk
CHIP_myelo_adj <-glm(Case_Control ~ CHIP + Age + Gender + BaseANC + BaseHGB + BasePLT + BaseWBC + Prior_chemo + Prior_rad + MAX2heme, data = global_data, family = binomial(link='logit'))
summary(CHIP_myelo_adj)
exp(cbind(coef(CHIP_myelo_adj), confint(CHIP_myelo_adj)))

#Difference in baseline ANC between CHIP+ and CHIP-
group_by(global_data, CHIP) %>%
  summarise(
    count = n(),
    median = median(BaseANC, na.rm = TRUE),
    IQR = IQR(BaseWBC, na.rm = TRUE) # WBC or ANC----
  )

library(ggpubr)
ggboxplot(global_data, x = "CHIP", y = "BaseANC", 
          color = "CHIP", palette = c("#00AFBB", "#E7B800"),
          ylab = "BaseANC", xlab = "CHIP status")

res <- wilcox.test(BaseANC ~ CHIP, data = global_data,
                   exact = FALSE)
res

#Difference in baseline HGB between CHIP+ and CHIP-
group_by(global_data, CHIP) %>%
  summarise(
    count = n(),
    median = median(BaseHGB, na.rm = TRUE),
    IQR = IQR(BaseHGB, na.rm = TRUE)
  )

res <- wilcox.test(BaseHGB ~ CHIP, data = global_data,
                   exact = FALSE)
res

#Difference in baseline PLT between CHIP+ and CHIP-
group_by(global_data, CHIP) %>%
  summarise(
    count = n(),
    median = median(BasePLT, na.rm = TRUE),
    IQR = IQR(BasePLT, na.rm = TRUE)
  )

ggboxplot(global_data, x = "CHIP", y = "BasePLT",
          color = "CHIP", palette = c("#00AFBB", "#E7B800"),
          ylab = "BaseANC", xlab = "CHIP status")

res <- wilcox.test(BasePLT ~ CHIP, data = global_data,
                   exact = FALSE)
res

#Difference in baseline WBC between CHIP+ and CHIP-
group_by(global_data, CHIP) %>%
  summarise(
    count = n(),
    median = median(BaseWBC, na.rm = TRUE),
    IQR = IQR(BaseWBC, na.rm = TRUE)
  )

res <- wilcox.test(BaseWBC ~ CHIP, data = global_data,
                   exact = FALSE)
res

#Difference in change in ANC between CHIP+ and CHIP-
group_by(global_data, CHIP) %>%
  summarise(
    count = n(),
    median = median(ChangeANC, na.rm = TRUE),
    IQR = IQR(ChangeANC, na.rm = TRUE)
  )

res <- wilcox.test(ChangeANC ~ CHIP, data = global_data,
                   exact = FALSE)
res

# #Difference in change in ANC between CHPD+ and CHPD-
# library(dplyr)
# group_by(global_data, CHPD) %>%
#   summarise(
#     count = n(),
#     median = median(ChangeANC, na.rm = TRUE),
#     IQR = IQR(ChangeANC, na.rm = TRUE)
#   )
# 
# res <- wilcox.test(ChangeANC ~ CHPD, data = global_data,
#                    exact = FALSE)
# res

#Difference in change in HGB between CHIP+ and CHIP-
library(dplyr)
group_by(global_data, CHIP) %>%
  summarise(
    count = n(),
    median = median(ChangeHGB, na.rm = TRUE),
    IQR = IQR(ChangeHGB, na.rm = TRUE)
  )

res <- wilcox.test(ChangeHGB ~ CHIP, data = global_data,
                   exact = FALSE)
res

# #Difference in change in HGB between CHPD+ and CHPD-
# group_by(global_data, CHPD) %>%
#   summarise(
#     count = n(),
#     median = median(ChangeHGB, na.rm = TRUE),
#     IQR = IQR(ChangeHGB, na.rm = TRUE)
#   )
# 
# res <- wilcox.test(ChangeHGB ~ CHPD, data = global_data,
#                    exact = FALSE)
# res

#Difference in change in PLT between CHIP+ and CHIP-
group_by(global_data, CHIP) %>%
  summarise(
    count = n(),
    median = median(ChangePLT, na.rm = TRUE),
    IQR = IQR(ChangePLT, na.rm = TRUE)
  )

res <- wilcox.test(ChangePLT ~ CHIP, data = global_data,
                   exact = FALSE)
res

# #Difference in change in PLT between CHPD+ and CHPD-
# group_by(global_data, CHPD) %>%
#   summarise(
#     count = n(),
#     median = median(ChangePLT, na.rm = TRUE),
#     IQR = IQR(ChangePLT, na.rm = TRUE)
#   )
# 
# res <- wilcox.test(ChangePLT ~ CHPD, data = global_data,
#                    exact = FALSE)
# res

#Difference in change in WBC between CHIP+ and CHIP-
library(dplyr)
group_by(global_data, CHIP) %>%
  summarise(
    count = n(),
    median = median(ChangeWBC, na.rm = TRUE),
    IQR = IQR(ChangeWBC, na.rm = TRUE)
  )

res <- wilcox.test(ChangeWBC ~ CHIP, data = global_data,
                   exact = FALSE)
res

# #Difference in change in WBC between CHPD+ and CHPD-
# library(dplyr)
# group_by(global_data, CHPD) %>%
#   summarise(
#     count = n(),
#     median = median(ChangeWBC, na.rm = TRUE),
#     IQR = IQR(ChangeWBC, na.rm = TRUE)
#   )
# 
# res <- wilcox.test(ChangeWBC ~ CHPD, data = global_data,
#                    exact = FALSE)
# res

#Difference in AGE between CHIP+ and CHIP-
library(dplyr)
group_by(global_data, CHIP) %>%
  summarise(
    count = n(),
    median = median(Age, na.rm = TRUE),
    IQR = IQR(Age, na.rm = TRUE)
  )

res <- wilcox.test(Age ~ CHIP, data = global_data,
                   exact = FALSE)
res

# #Difference in change in PLT between CHPD+ and CHPD-
# library(dplyr)
# group_by(global_data, CHPD) %>%
#   summarise(
#     count = n(),
#     median = median(Age, na.rm = TRUE),
#     IQR = IQR(Age, na.rm = TRUE)
#   )
# 
# res <- wilcox.test(Age ~ CHPD, data = global_data,
#                    exact = FALSE)
# res

#####Fisher's Exact Tests/Chi-sq for Categorical Variables

##Neutropenia
table(global_data$CHIP, global_data$Neutro)
CHIPneutro <- table(global_data$CHIP, global_data$Neutro)
summary(CHIPneutro)
#fisher.test(table (global_data$CHIP, global_data$Neutro))

##Anemia
table(global_data$CHIP, global_data$Anemia)
CHIPanemia <- table(global_data$CHIP, global_data$Anemia)
fisher.test(table (global_data$CHIP, global_data$Anemia))

##Thrombocytopenia
table(global_data$CHIP, global_data$Thrombo)
CHIPthrombo <- table(global_data$CHIP, global_data$Thrombo)
fisher.test(table (global_data$CHIP, global_data$Thrombo))

##Leukopenia
table(global_data$CHIP, global_data$Leuko)
CHIPleuko <- table(global_data$CHIP, global_data$Leuko)
summary(CHIPleuko)
#fisher.test(table (global_data$CHIP, global_data$Leuko))

##Metastasis
table(global_data$CHIP, global_data$Mets)
CHIPmet <- table(global_data$CHIP, global_data$Mets)
summary(CHIPmet)
# fisher.test(table (global_data$CHIP, global_data$Met))

res.logit1c <- glm(CHIP ~ Mets, data = global_data, family = "binomial")
summary(res.logit1c)$coef
exp(cbind(coef(res.logit1c), confint(res.logit1c)))

##Adjusted - CHIP and mets
CHIP_myelo_adj <-glm(Mets ~ CHIP + Age + Smoking + Prior_chemo + Prior_rad, data = global_data, family = binomial(link='logit'))
summary(CHIP_myelo_adj)
exp(cbind(coef(CHIP_myelo_adj), confint(CHIP_myelo_adj)))


##Gender  
table(global_data$CHIP, global_data$Gender)
CHIPGender <- table(global_data$CHIP, global_data$Gender)
summary(CHIPGender)
# fisher.test(table (global_data$CHIP, global_data$Gender))

##Race  
table(global_data$CHIP, global_data$Race)
CHIPRace <- table(global_data$CHIP, global_data$Race)
# summary(CHIPRace)
fisher.test(table (global_data$CHIP, global_data$Race))

##Smoking  
table(global_data$CHIP, global_data$Smoking)
CHIPSmoking <- table(global_data$CHIP, global_data$Smoking)
summary(CHIPSmoking)
# fisher.test(table (global_data$CHIP, global_data$Smoking))

##Prior Chemo
table(global_data$CHIP, global_data$Prior_chemo)
CHIPchemo <- table(global_data$CHIP, global_data$Prior_chemo)
summary(CHIPchemo)
# fisher.test(table (global_data$CHIP, global_data$Prior_chemo))

##Prior Radiation
table(global_data$CHIP, global_data$Prior_rad)
CHIPrad <- table(global_data$CHIP, global_data$Prior_rad)
summary(CHIPrad)
# fisher.test(table (global_data$CHIP, global_data$Prior_rad))


####Compare baseline b/t Case_Control - MCC + UNC


global_data$Case_Control <- factor (global_data$Case_Control, labels=c("Control", "Case"))

##Age by Case_Control 
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(Age, na.rm = TRUE),
    IQR = IQR(Age, na.rm = TRUE)
  )

res <- wilcox.test(Age ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Sex by Case_Control
table(global_data$Case_Control, global_data$Gender)
Case_Controlsex <- table(global_data$Case_Control, global_data$Gender)
summary(Case_Controlsex)
#fisher.test(table (global_data$Case_Control, global_data$Gender))

##Race by Case_Control
table(global_data$Case_Control, global_data$Race)
Case_Controlrace <- table(global_data$Case_Control, global_data$Race)
# summary(Case_Controlrace)
fisher.test(table (global_data$Case_Control, global_data$Race))

##Smoking by Case_Control 
table(global_data$Case_Control, global_data$Smoking)
Case_ControlSmoking <- table(global_data$Case_Control, global_data$Smoking)
summary(Case_ControlSmoking)
# fisher.test(table (global_data$Case_Control, global_data$Smoking))

##Metastasis by Case_Control
table(global_data$Case_Control, global_data$Mets)
Case_ControlMets <- table(global_data$Case_Control, global_data$Mets)
summary(Case_ControlMets)
# fisher.test(table (global_data$Case_Control, global_data$Mets))

##Prior Chemotherapy by Case_Control
table(global_data$Case_Control, global_data$Prior_chemo)
Case_Controlchemo <- table(global_data$Case_Control, global_data$Prior_chemo)
summary(Case_Controlchemo)
# fisher.test(table (global_data$Case_Control, global_data$Prior_chemo))

##Prior Radiation by Case_Control
table(global_data$Case_Control, global_data$Prior_rad)
Case_Controlrad <- table(global_data$Case_Control, global_data$Prior_rad)
summary(Case_Controlrad)
# fisher.test(table (global_data$Case_Control, global_data$Prior_rad))

##MAX2-heme by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(MAX2heme, na.rm = TRUE),
    IQR = IQR(MAX2heme, na.rm = TRUE)
  )
res <- wilcox.test(MAX2heme ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Baseline ANC by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(BaseANC, na.rm = TRUE),
    IQR = IQR(BaseANC, na.rm = TRUE)
  )
res <- wilcox.test(BaseANC ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Baseline HGB by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(BaseHGB, na.rm = TRUE),
    IQR = IQR(BaseHGB, na.rm = TRUE)
  )
res <- wilcox.test(BaseHGB ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Baseline PLT by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(BasePLT, na.rm = TRUE),
    IQR = IQR(BasePLT, na.rm = TRUE)
  )
res <- wilcox.test(BasePLT ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Baseline WBC by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(BaseWBC, na.rm = TRUE),
    IQR = IQR(BaseWBC, na.rm = TRUE)
  )
res <- wilcox.test(BaseWBC ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Change in ANC by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(ChangeANC, na.rm = TRUE),
    IQR = IQR(ChangeANC, na.rm = TRUE)
  )
res <- wilcox.test(ChangeANC ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Change in HGB by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(ChangeHGB, na.rm = TRUE),
    IQR = IQR(ChangeHGB, na.rm = TRUE)
  )
res <- wilcox.test(ChangeHGB ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Change in PLT by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(ChangePLT, na.rm = TRUE),
    IQR = IQR(ChangePLT, na.rm = TRUE)
  )
res <- wilcox.test(ChangePLT ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Change in WBC by Case_Control
group_by(global_data, Case_Control) %>%
  summarise(
    count = n(),
    median = median(ChangeWBC, na.rm = TRUE),
    IQR = IQR(ChangeWBC, na.rm = TRUE)
  )
res <- wilcox.test(ChangeWBC ~ Case_Control, data = global_data,
                   exact = FALSE)
res

##Neutopenia by Case_Control
table(global_data$Case_Control, global_data$Neutro)
Case_ControlNeutro <- table(global_data$Case_Control, global_data$Neutro)
summary(Case_ControlNeutro)
# fisher.test(table (global_data$Case_Control, global_data$Neutro))

##Anemia by Case_Control
table(global_data$Case_Control, global_data$Anemia)
Case_ControlAnemia <- table(global_data$Case_Control, global_data$Anemia)
# summary(Case_ControlAnemia)
fisher.test(table (global_data$Case_Control, global_data$Anemia))

##Thrombocytopenia by Case_Control
table(global_data$Case_Control, global_data$Thrombo)
Case_ControlThrombo <- table(global_data$Case_Control, global_data$Thrombo)
# summary(Case_ControlThrombo)
fisher.test(table (global_data$Case_Control, global_data$Thrombo))

##Leukopenia by Case_Control
table(global_data$Case_Control, global_data$Leuko)
Case_ControlLeuko <- table(global_data$Case_Control, global_data$Leuko)
summary(Case_ControlLeuko)
# fisher.test(table (global_data$Case_Control, global_data$Leuko))
```